"""Grounded generation for POST /crisis/analyze.

Takes Module 01's live event feed, retrieves the emergency procedure chunk
that best matches those events, and asks the instruct model for a short
root cause statement grounded in that chunk. Nothing here fabricates a
cause: if retrieval finds no matching procedure documentation, this module
refuses to generate a root cause rather than let the model guess (see
`analyze_crisis`), the same no-hallucination discipline
`app.services.telemetry` follows.

`root_cause` is generated by the instruct model from the retrieved chunk's
`page_content` — the semantically-matched excerpt is exactly what should
ground that statement. `steps` is populated from
`app.services.extraction.extract_procedure_steps`, deterministically, not
generated by the model — the step list a crew acts on should be exactly
what the procedure document says, not a paraphrase.

Dev plan Aug 20, Task 1 shipped `steps` extracted from `page_content`, the
single retrieved chunk's own text. Task 2 ("Ground the procedure steps in
the retrieved procedure document") found that insufficient for two
reasons, not just the one Task 1 anticipated:

1. A long procedure document can span more than one embedded chunk, so a
   single retrieval hit can miss steps that landed in a different chunk.
2. More fundamentally, `app.services.ingestion.chunk_text` collapses every
   whitespace run — including newlines — before packing a document's words
   into chunks. `extract_procedure_steps` matches step markers per line,
   so a chunk's `page_content` (which has no line breaks left at all) is
   parsed as a single line, and only ever yields a step if that whole line
   happens to open with a step marker. Verified against a real (not
   mocked) `chunk_text` run over `sample_emergency_procedure.txt` at the
   production default chunk size: `page_content` yields zero steps, versus
   ten out of the raw, un-chunked document.

Both are solved the same way: `steps` is extracted from the retrieved
chunk's `doc_text` metadata field (see `app.services.ingestion.Chunk`) —
the full, un-chunked source document, carried alongside every chunk
specifically so a module like this one doesn't have to depend on chunk
boundaries or chunk-collapsed formatting for structured extraction.
`page_content` still grounds `root_cause`; only `steps` reads `doc_text`.
"""

from __future__ import annotations

from app.schemas import CrisisAnalyzeResponse, CrisisEvent
from app.services.extraction import extract_procedure_steps
from app.services.vector_store import get_vector_store
from app.services.watsonx import get_instruct_model

_PROMPT_TEMPLATE = """You are the crisis analyst for The North Star, a deep space \
habitat's mission console. You turn a live event feed into a short, plain-language \
root cause statement the crew can act on immediately.

Base your root cause statement strictly on the emergency procedure documentation and \
event feed below. Do not invent a cause, mechanism, or event that is not supported by \
this documentation or the feed. Keep the statement to one or two sentences.

Emergency procedure documentation:
{chunk_text}

Event feed (most recent last):
{events}

Root cause statement:"""


def _format_events(events: list[CrisisEvent]) -> str:
    return "\n".join(
        f"[{event.timestamp}] {event.sector}: {event.description}" for event in events
    )


def _build_retrieval_query(events: list[CrisisEvent]) -> str:
    """Build the text used to semantically match emergency procedure documentation.

    Procedure chunks carry no `sector` in their metadata (see
    `app.services.ingestion.Chunk.metadata`) — they're free text tagged only
    with `doc_id`/`doc_type`/`chunk_index`. So "the matching procedure" is
    found by similarity between this query text and the embedded
    documentation, not by an exact metadata match, the same approach
    `app.services.telemetry._build_retrieval_query` takes for sector specs.
    """
    return "\n".join(
        f"{event.sector} sector event: {event.description}" for event in events
    )


def _build_prompt(chunk_text: str, events: list[CrisisEvent]) -> str:
    return _PROMPT_TEMPLATE.format(chunk_text=chunk_text, events=_format_events(events))


def _source_line(metadata: dict) -> str:
    return f"{metadata['doc_type']}:{metadata['doc_id']}#chunk{metadata['chunk_index']}"


def analyze_crisis(events: list[CrisisEvent]) -> CrisisAnalyzeResponse:
    """Retrieve the matching emergency procedure and generate a grounded root cause.

    Raises `LookupError` if no `procedure` documentation is found for this
    event feed — callers (see `app.main`) should map that to a 404 rather
    than fall back to an ungrounded root cause. `steps` is extracted
    deterministically from the retrieved chunk's `doc_text` metadata (the
    full source document, not the chunk's own `page_content`); see the
    module docstring for why.
    """
    query = _build_retrieval_query(events)
    hits = get_vector_store().similarity_search(query, k=1, expr="doc_type == 'procedure'")
    if not hits:
        raise LookupError(
            "No emergency procedure documentation found matching this event feed. "
            "Ingest procedure documents via POST /ingest first."
        )

    chunk = hits[0]
    prompt = _build_prompt(chunk.page_content, events)
    message = get_instruct_model().invoke(prompt)
    root_cause = str(message.content).strip()
    steps = extract_procedure_steps(chunk.metadata["doc_text"])

    return CrisisAnalyzeResponse(
        root_cause=root_cause,
        steps=steps,
        source=_source_line(chunk.metadata),
    )
