"""Grounded generation for POST /crisis/analyze.

Takes Module 01's live event feed, retrieves the emergency procedure chunk
that best matches those events, and asks the instruct model for a short
root cause statement grounded in that chunk. Nothing here fabricates a
cause: if retrieval finds no matching procedure documentation, this module
refuses to generate a root cause rather than let the model guess (see
`analyze_crisis`), the same no-hallucination discipline
`app.services.telemetry` follows.

`root_cause` is generated by the instruct model from the retrieved chunks'
`page_content` — the semantically-matched excerpts are exactly what should
ground that statement. `steps` is populated from
`app.services.extraction.extract_procedure_steps`, deterministically, not
generated by the model — the step list a crew acts on should be exactly
what the procedure document says, not a paraphrase.

Dev plan Aug 20, Task 1 shipped `steps` extracted from `page_content`, the
single retrieved chunk's own text. Task 2 ("Ground the procedure steps in
the retrieved procedure document") found that insufficient for two
reasons, not just the one Task 1 anticipated:

1. A long procedure document can span more than one embedded chunk, so a
   single retrieval hit can miss steps that landed in a different chunk.
2. More fundamentally, `app.services.ingestion.chunk_text` collapses every
   whitespace run — including newlines — before packing a document's words
   into chunks. `extract_procedure_steps` matches step markers per line,
   so a chunk's `page_content` (which has no line breaks left at all) is
   parsed as a single line, and only ever yields a step if that whole line
   happens to open with a step marker. Verified against a real (not
   mocked) `chunk_text` run over `sample_emergency_procedure.txt` at the
   production default chunk size: `page_content` yields zero steps, versus
   ten out of the raw, un-chunked document.

Both are solved the same way: `steps` is extracted from each retrieved
chunk's `doc_text` metadata field (see `app.services.ingestion.Chunk`) —
the full, un-chunked source document, carried alongside every chunk
specifically so a module like this one doesn't have to depend on chunk
boundaries or chunk-collapsed formatting for structured extraction.
`page_content` still grounds `root_cause`; only `steps` reads `doc_text`.

Compound scenarios: Module 01's frontend can now inject more than one
failure point at once (see `scenarioLibrary` in mission-console.html), so
a single event feed can carry events from several distinct sectors in one
call. `analyze_crisis` groups events by `CrisisEvent.sector` and retrieves
one procedure match per distinct sector (capped at `_MAX_SECTORS`, so a
feed can't blow up the prompt size or the number of retrieval calls),
rather than the single blended `k=1` retrieval this module used when only
one failure point could ever be injected. Every matched chunk is handed to
the instruct model together so it can synthesize one compound root-cause
statement grounded across all of them — never in a sector that retrieved
nothing. `steps` and `sources`/`contributing_causes` are built the same
deterministic way as before, just concatenated across every matched
sector in the order sectors first appeared in the feed, rather than read
off a single chunk. `step_counts` carries, in that same order, how many of
the concatenated `steps` came from each matched sector, so a caller (the
frontend's merged checklist) can label/group steps by source without the
flat `steps` list losing the single continuous ordering the existing
checklist-completion/out-of-order tracking depends on.

A sector with no matching procedure documentation is dropped rather than
failing the whole request: `LookupError` (mapped to a 404 by `app.main`)
is only raised if *no* sector in the feed matched anything at all. This
mirrors the same "don't let the model guess" discipline as before, just
applied per matched cause instead of per request — a compound emergency
where only some of the concurrent failures have ingested procedure docs
should still return a grounded (if partial) answer for the ones that do,
rather than refusing to say anything about any of them.
"""

from __future__ import annotations

from app.schemas import CrisisAnalyzeResponse, CrisisEvent
from app.services.extraction import extract_procedure_steps
from app.services.vector_store import get_vector_store
from app.services.watsonx import get_instruct_model

# Caps how many distinct sectors in one event feed get their own retrieval
# call and their own slot in the synthesis prompt. Bounds both the number
# of round trips to the vector store and the prompt size a compound
# scenario can produce — see the module docstring's "Compound scenarios"
# section. The frontend's scenario library (mission-console.html) currently
# offers 5 selectable failure points (hull, oxygen/ECLSS, water/thermal,
# power, nav/comms); this cap is set below that count so an operator
# selecting every failure point at once still gets a bounded prompt rather
# than every selection guaranteed its own slot — raise it if the library
# grows and every concurrent selection should always be individually grounded.
_MAX_SECTORS = 4

_PROMPT_TEMPLATE = """You are the crisis analyst for The North Star, a deep space \
habitat's mission console. You turn a live event feed into a short, plain-language \
root cause statement the crew can act on immediately.

Base your root cause statement strictly on the emergency procedure documentation and \
event feed below. Do not invent a cause, mechanism, or event that is not supported by \
this documentation or the feed. The documentation may cover more than one distinct \
failure — if it does, briefly cover each one the feed actually shows evidence of, and \
note how they interact only if the documentation itself supports that. If only one \
failure is grounded, describe just that one. Keep the statement to one or two \
sentences per failure covered.

Emergency procedure documentation:
{chunks_text}

Event feed (most recent last):
{events}

Root cause statement:"""


def _format_events(events: list[CrisisEvent]) -> str:
    return "\n".join(
        f"[{event.timestamp}] {event.sector}: {event.description}" for event in events
    )


def _group_events_by_sector(
    events: list[CrisisEvent], max_sectors: int = _MAX_SECTORS
) -> dict[str, list[CrisisEvent]]:
    """Group events by `sector`, preserving first-seen sector order.

    A single-failure feed (today's default demo scenario) always produces
    exactly one group, so this is a no-op wrapper around the original
    single-cause behavior. A compound feed produces one group per distinct
    failure point the frontend interleaved into the feed. Capped at
    `max_sectors` groups — extra sectors beyond the cap are dropped from
    retrieval entirely (not merged into another sector's group), since a
    dropped sector still shows up in `events` fed to the synthesis prompt
    via `_format_events`, just without its own grounded procedure match.
    """
    groups: dict[str, list[CrisisEvent]] = {}
    for event in events:
        groups.setdefault(event.sector, []).append(event)
    if len(groups) <= max_sectors:
        return groups
    kept_sectors = list(groups.keys())[:max_sectors]
    return {sector: groups[sector] for sector in kept_sectors}


def _build_retrieval_query(events: list[CrisisEvent]) -> str:
    """Build the text used to semantically match emergency procedure documentation.

    Procedure chunks carry no `sector` in their metadata (see
    `app.services.ingestion.Chunk.metadata`) — they're free text tagged only
    with `doc_id`/`doc_type`/`chunk_index`. So "the matching procedure" is
    found by similarity between this query text and the embedded
    documentation, not by an exact metadata match, the same approach
    `app.services.telemetry._build_retrieval_query` takes for sector specs.

    Called once per sector group (see `_group_events_by_sector`), not once
    for the whole feed — `events` here is one sector's events, so a
    compound feed builds one query per distinct failure point instead of
    one blended query that a single dominant event could drown the others
    out of.
    """
    return "\n".join(
        f"{event.sector} sector event: {event.description}" for event in events
    )


def _format_chunks(matched: list[tuple[str, object]]) -> str:
    """Render every matched (sector, chunk) pair as a labeled excerpt block.

    Labeling each excerpt with its sector lets the synthesis prompt (and,
    if useful later, a human reviewer) tell which retrieved documentation
    grounds which part of a compound root-cause statement, without the
    model having to re-derive that mapping itself.
    """
    return "\n\n".join(
        f"[{sector}]\n{chunk.page_content}" for sector, chunk in matched
    )


def _build_prompt(matched: list[tuple[str, object]], events: list[CrisisEvent]) -> str:
    return _PROMPT_TEMPLATE.format(
        chunks_text=_format_chunks(matched), events=_format_events(events)
    )


def _source_line(metadata: dict) -> str:
    return f"{metadata['doc_type']}:{metadata['doc_id']}#chunk{metadata['chunk_index']}"


def _contributing_cause_line(sector: str, metadata: dict) -> str:
    """Deterministic "which sector, grounded in which document" label.

    Not model output — a plain composition of the sector this chunk was
    retrieved for and its `_source_line`. Lets the frontend group/label a
    compound response's checklist by which failure point each step came
    from, the same source-attribution discipline `sources` already
    follows, just paired with the sector it answers for.
    """
    return f"{sector}: {_source_line(metadata)}"


def analyze_crisis(events: list[CrisisEvent]) -> CrisisAnalyzeResponse:
    """Retrieve every matching emergency procedure and generate a grounded root cause.

    Groups `events` by sector (see `_group_events_by_sector`) and retrieves
    up to one procedure chunk per distinct sector, deduplicated by
    `doc_id` so two sectors that happen to match the same document don't
    double-count it. Raises `LookupError` only if *no* sector matched
    anything — callers (see `app.main`) should map that to a 404 rather
    than fall back to an ungrounded root cause. A partial match (some
    sectors grounded, others not) still returns a response, grounded only
    in what matched; see the module docstring for why.

    `steps` is extracted deterministically from each matched chunk's
    `doc_text` metadata (the full source document, not the chunk's own
    `page_content`) and concatenated in sector-match order; see the module
    docstring for why `doc_text` rather than `page_content`.
    """
    groups = _group_events_by_sector(events)

    store = get_vector_store()
    matched: list[tuple[str, object]] = []
    seen_doc_ids: set[str] = set()
    for sector, sector_events in groups.items():
        query = _build_retrieval_query(sector_events)
        hits = store.similarity_search(query, k=1, expr="doc_type == 'procedure'")
        if not hits:
            continue
        chunk = hits[0]
        doc_id = chunk.metadata["doc_id"]
        if doc_id in seen_doc_ids:
            continue
        seen_doc_ids.add(doc_id)
        matched.append((sector, chunk))

    if not matched:
        raise LookupError(
            "No emergency procedure documentation found matching this event feed. "
            "Ingest procedure documents via POST /ingest first."
        )

    prompt = _build_prompt(matched, events)
    message = get_instruct_model().invoke(prompt)
    root_cause = str(message.content).strip()

    steps: list[str] = []
    step_counts: list[int] = []
    for _, chunk in matched:
        matched_steps = extract_procedure_steps(chunk.metadata["doc_text"])
        steps.extend(matched_steps)
        step_counts.append(len(matched_steps))

    sources = [_source_line(chunk.metadata) for _, chunk in matched]
    contributing_causes = [
        _contributing_cause_line(sector, chunk.metadata) for sector, chunk in matched
    ]

    return CrisisAnalyzeResponse(
        root_cause=root_cause,
        steps=steps,
        step_counts=step_counts,
        sources=sources,
        contributing_causes=contributing_causes,
    )
