"""Grounded generation for POST /crisis/analyze.

Takes Module 01's live event feed, retrieves the emergency procedure chunk
that best matches those events, and asks the instruct model for a short
root cause statement grounded in that chunk. Nothing here fabricates a
cause: if retrieval finds no matching procedure documentation, this module
refuses to generate a root cause rather than let the model guess (see
`analyze_crisis`), the same no-hallucination discipline
`app.services.telemetry` follows.

Dev plan Aug 20, Task 1 scope: retrieval + a grounded root cause statement.
`steps` is populated from `app.services.extraction.extract_procedure_steps`
run on the single retrieved chunk's text, not generated by the model — the
step list a crew acts on should be exactly what the procedure document
says, not a paraphrase. That single-chunk limitation (a long procedure can
span more than one embedded chunk, so one retrieval hit can miss steps)
is what Task 2 ("Ground the procedure steps in the retrieved procedure
document") addresses in a separate follow-up commit; this module doesn't
attempt it yet.
"""

from __future__ import annotations

from app.schemas import CrisisAnalyzeResponse, CrisisEvent
from app.services.extraction import extract_procedure_steps
from app.services.vector_store import get_vector_store
from app.services.watsonx import get_instruct_model

_PROMPT_TEMPLATE = """You are the crisis analyst for The North Star, a deep space \
habitat's mission console. You turn a live event feed into a short, plain-language \
root cause statement the crew can act on immediately.

Base your root cause statement strictly on the emergency procedure documentation and \
event feed below. Do not invent a cause, mechanism, or event that is not supported by \
this documentation or the feed. Keep the statement to one or two sentences.

Emergency procedure documentation:
{chunk_text}

Event feed (most recent last):
{events}

Root cause statement:"""


def _format_events(events: list[CrisisEvent]) -> str:
    return "\n".join(
        f"[{event.timestamp}] {event.sector}: {event.description}" for event in events
    )


def _build_retrieval_query(events: list[CrisisEvent]) -> str:
    """Build the text used to semantically match emergency procedure documentation.

    Procedure chunks carry no `sector` in their metadata (see
    `app.services.ingestion.Chunk.metadata`) — they're free text tagged only
    with `doc_id`/`doc_type`/`chunk_index`. So "the matching procedure" is
    found by similarity between this query text and the embedded
    documentation, not by an exact metadata match, the same approach
    `app.services.telemetry._build_retrieval_query` takes for sector specs.
    """
    return "\n".join(
        f"{event.sector} sector event: {event.description}" for event in events
    )


def _build_prompt(chunk_text: str, events: list[CrisisEvent]) -> str:
    return _PROMPT_TEMPLATE.format(chunk_text=chunk_text, events=_format_events(events))


def _source_line(metadata: dict) -> str:
    return f"{metadata['doc_type']}:{metadata['doc_id']}#chunk{metadata['chunk_index']}"


def analyze_crisis(events: list[CrisisEvent]) -> CrisisAnalyzeResponse:
    """Retrieve the matching emergency procedure and generate a grounded root cause.

    Raises `LookupError` if no `procedure` documentation is found for this
    event feed — callers (see `app.main`) should map that to a 404 rather
    than fall back to an ungrounded root cause. `steps` is extracted
    deterministically from the retrieved chunk's own text; see the module
    docstring for why it isn't model-generated and what's out of scope for
    this commit.
    """
    query = _build_retrieval_query(events)
    hits = get_vector_store().similarity_search(query, k=1, expr="doc_type == 'procedure'")
    if not hits:
        raise LookupError(
            "No emergency procedure documentation found matching this event feed. "
            "Ingest procedure documents via POST /ingest first."
        )

    chunk = hits[0]
    prompt = _build_prompt(chunk.page_content, events)
    message = get_instruct_model().invoke(prompt)
    root_cause = str(message.content).strip()
    steps = extract_procedure_steps(chunk.page_content)

    return CrisisAnalyzeResponse(
        root_cause=root_cause,
        steps=steps,
        source=_source_line(chunk.metadata),
    )
