"""Grounded generation for POST /triage.

Takes Module 03's crew member id and plain-English symptom report, retrieves
that crew member's file and the treatment protocol chunk that best matches
the reported symptoms, and asks the instruct model for a short triage lead
grounded in both. Nothing here fabricates a diagnosis or a treatment: if
either retrieval comes up empty, this module refuses to generate a triage
lead rather than let the model guess (see `run_triage`), the same
no-hallucination discipline `app.services.telemetry` and `app.services.
crisis` follow.

Two retrievals happen, and they are not the same kind of lookup:

- The crew file is looked up by an *exact* match on `crew_member_id`
  against the ingested `MissionDocument.id` for that crew member's file
  (`app.schemas.TriageRequest.crew_member_id`'s docstring covers the
  pattern constraint that also protects this from expr injection) — unlike
  a sector spec or a procedure, there is exactly one right crew file for a
  given crew member, so this is not a semantic search.
- The treatment protocol is matched *semantically* against the symptom
  report text, the same way `app.services.crisis` matches an emergency
  procedure against an event feed: protocol chunks carry no
  symptom/condition tag in their metadata (see `app.services.
  ingestion.Chunk.metadata`), only `doc_id`/`doc_type`/`chunk_index`.

`triage_lead` is generated by the instruct model from the retrieved
protocol chunk's `page_content` plus the retrieved crew file's full
`doc_text` (name, role, vitals, allergy line — whatever the file records),
so the model can ground its lead in the crew member's actual record rather
than the symptom report alone. `instructions` is populated from
`app.services.extraction.extract_procedure_steps` run against the protocol
chunk's `doc_text` metadata, not its `page_content` — reading `doc_text`
from the start applies the grounding fix dev plan Aug 20 Task 2 had to add
to `/crisis/analyze` after the fact (see `app.services.crisis`'s module
docstring for why `page_content` alone loses both chunk-boundary steps and
all line structure).

`allergy_check` (dev plan Aug 21 Task 2, "Add the allergy cross check and
the source reference line to the triage response") cross-checks the
retrieved crew file's allergy list against the retrieved protocol's text —
see `_check_allergies`. It is deterministic, not model-generated: a
safety-relevant field should report exactly what the documents say, the
same reasoning `instructions` already follows for step lists. `source`
(also Task 2) cites both retrieved documents — see `_source_line` — since
triage, unlike telemetry/crisis, grounds its response in two documents
rather than one. `confidence` is computed here from the protocol match's
retrieval strength alone (no nominal-band signal applies to a symptom
report the way it does to a sector reading), since triage has no
dedicated confidence-scoring task on the calendar the way telemetry and
crisis's follow-up tasks did.
"""

from __future__ import annotations

import re

from app.schemas import TriageResponse
from app.services.extraction import extract_allergies, extract_procedure_steps
from app.services.vector_store import get_vector_store, relevance_score_hits_or_empty
from app.services.watsonx import get_instruct_model

_PROMPT_TEMPLATE = """You are the medical triage assistant for The North Star, a deep \
space habitat's mission console. You turn a crew member's symptom report and medical \
file into a short, plain-language triage lead the crew can act on immediately.

Base your triage lead strictly on the treatment protocol documentation and crew file \
below. Do not invent a diagnosis, mechanism, or treatment that is not supported by this \
documentation. Keep the lead to one or two sentences.

Treatment protocol documentation:
{protocol_text}

Crew file:
{crew_file_text}

Symptom report:
{symptom_report}

Triage lead:"""


def _build_protocol_query(symptom_report: str) -> str:
    """Build the text used to semantically match treatment protocol documentation.

    Protocol chunks carry no symptom/condition tag in their metadata (see
    `app.services.ingestion.Chunk.metadata`) — they're free text tagged
    only with `doc_id`/`doc_type`/`chunk_index`. So "the matching protocol"
    is found by similarity between the symptom report and the embedded
    documentation, the same approach `app.services.crisis.
    _build_retrieval_query` takes for emergency procedures.
    """
    return f"Symptom report: {symptom_report}"


def _build_prompt(protocol_text: str, crew_file_text: str, symptom_report: str) -> str:
    return _PROMPT_TEMPLATE.format(
        protocol_text=protocol_text,
        crew_file_text=crew_file_text,
        symptom_report=symptom_report,
    )


def _retrieval_strength(relevance_score: float) -> float:
    """Normalize a retrieval relevance score to a [0, 1] confidence signal.

    Same normalization and same defensive clamp as
    `app.services.telemetry._retrieval_strength` — see that function's
    docstring for why the clamp is defensive rather than provably
    redundant. Rounded to two decimal places for the API response, same as
    telemetry's `_combine_confidence`.
    """
    return round(max(0.0, min(1.0, relevance_score)), 2)


def _check_allergies(protocol_text: str, allergies: list[str]) -> str:
    """Cross-check a crew member's recorded allergies against a treatment protocol.

    Deterministic text matching, not a model call: this is a
    safety-relevant field, so it reports only what the documents literally
    say, the same discipline `extract_procedure_steps` already applies to
    `instructions`. Each allergen is searched for as a whole word/phrase,
    case-insensitively, in `protocol_text` (the protocol's full `doc_text`,
    not its `page_content` excerpt — same grounding-fix reasoning
    `run_triage` already applies when extracting `instructions`).

    This is plain substring/word-boundary matching, not a medical
    synonym or cross-reactivity lookup — it will not catch, for example,
    that a penicillin allergy also implicates amoxicillin. It only ever
    flags what the protocol text explicitly names.

    Returns one of three messages:

    - No allergies recorded on the crew file at all.
    - Allergies recorded, but none of them appear in the protocol text.
    - One or more recorded allergens appear in the protocol text — flagged
      as a conflict, naming every match (not just the first).
    """
    if not allergies:
        return "No known allergies on file for this crew member."

    matches = [
        allergen
        for allergen in allergies
        if re.search(rf"\b{re.escape(allergen)}\b", protocol_text, re.IGNORECASE)
    ]
    if matches:
        return (
            "CONFLICT: crew member has a recorded allergy to "
            f"{', '.join(matches)}, which appears in the recommended treatment. "
            "Confirm before administering."
        )

    return (
        "No conflict detected between recorded allergies "
        f"({', '.join(allergies)}) and this treatment protocol."
    )


def _source_line(metadata: dict) -> str:
    """Build a source reference line for a single retrieved chunk's metadata.

    Same format `app.services.telemetry`/`app.services.crisis` use:
    `f"{doc_type}:{doc_id}#chunk{chunk_index}"`.
    """
    return f"{metadata['doc_type']}:{metadata['doc_id']}#chunk{metadata['chunk_index']}"


def _combined_source(crew_metadata: dict, protocol_metadata: dict) -> str:
    """Build the `source` line for a triage response, citing both documents.

    Unlike telemetry/crisis, which each retrieve exactly one document,
    `/triage` grounds its response in two: the crew file (behind
    `allergy_check`, and part of `triage_lead`'s grounding) and the
    protocol (behind `triage_lead` and `instructions`). A single-document
    source line would misrepresent where the response came from, so both
    are cited, separated by `"; "`.
    """
    return f"{_source_line(crew_metadata)}; {_source_line(protocol_metadata)}"


def _crew_file_expr(crew_member_id: str) -> str:
    """Build the Milvus boolean expr for an exact crew-file lookup.

    `crew_member_id` is validated by `app.schemas.TriageRequest` against
    `^[a-z0-9_-]+$` before it ever reaches here, so it cannot contain a `'`
    or otherwise break out of this filter — this function does not
    re-validate, it relies on that schema-level constraint. Do not call it
    with unvalidated input.
    """
    return f"doc_type == 'crew_file' && doc_id == '{crew_member_id}'"


def run_triage(crew_member_id: str, symptom_report: str) -> TriageResponse:
    """Retrieve the crew member's file and a matching protocol, and generate a grounded lead.

    Raises `LookupError` if no crew file is found for `crew_member_id`, or
    if no `procedure`-type documentation matches the symptom report —
    callers (see `app.main`) should map either to a 404 rather than fall
    back to an ungrounded triage lead. The crew file is looked up first,
    since it's a cheap exact-match lookup — a request for an unknown crew
    member fails fast without attempting the semantic protocol search.
    """
    crew_hits = get_vector_store().similarity_search(
        symptom_report, k=1, expr=_crew_file_expr(crew_member_id)
    )
    if not crew_hits:
        raise LookupError(
            f"No crew file found for crew member '{crew_member_id}'. "
            "Ingest crew files via POST /ingest first."
        )
    crew_metadata = crew_hits[0].metadata
    crew_file_text = crew_metadata["doc_text"]
    allergies = extract_allergies(crew_file_text)

    protocol_query = _build_protocol_query(symptom_report)
    protocol_hits = relevance_score_hits_or_empty(
        get_vector_store(), protocol_query, k=1, expr="doc_type == 'procedure'"
    )
    if not protocol_hits:
        raise LookupError(
            "No treatment protocol found matching this symptom report. "
            "Ingest procedure documents via POST /ingest first."
        )
    protocol_chunk, relevance_score = protocol_hits[0]

    prompt = _build_prompt(protocol_chunk.page_content, crew_file_text, symptom_report)
    message = get_instruct_model().invoke(prompt)
    triage_lead = str(message.content).strip()
    protocol_text = protocol_chunk.metadata["doc_text"]
    instructions = extract_procedure_steps(protocol_text)
    allergy_check = _check_allergies(protocol_text, allergies)

    return TriageResponse(
        triage_lead=triage_lead,
        instructions=instructions,
        allergy_check=allergy_check,
        confidence=_retrieval_strength(relevance_score),
        source=_combined_source(crew_metadata, protocol_chunk.metadata),
    )
