"""Base Pydantic schemas shared across the API.

Endpoint-specific request/response models for the four module endpoints
(telemetry, crisis, triage, rationing) and the optional query endpoint are
added alongside their respective endpoints per the day-by-day build plan.
This module also holds the POST /ingest schemas, since ingestion is shared
infrastructure feeding every module's retrieval step rather than a single
module's endpoint.
"""

from enum import Enum

from pydantic import BaseModel, Field


class HealthResponse(BaseModel):
    """Response body for GET /health."""

    status: str
    backend: str


class DocumentType(str, Enum):
    """Kinds of mission documents accepted by POST /ingest."""

    PROCEDURE = "procedure"
    SECTOR_SPEC = "sector_spec"
    CREW_FILE = "crew_file"
    INCIDENT_RECORD = "incident_record"


class MissionDocument(BaseModel):
    """A single raw mission document submitted for ingestion."""

    id: str
    type: DocumentType
    text: str = Field(min_length=1)


class IngestRequest(BaseModel):
    """Request body for POST /ingest."""

    documents: list[MissionDocument]


class IngestResponse(BaseModel):
    """Response body for POST /ingest."""

    chunks_ingested: int


class TelemetryInterpretRequest(BaseModel):
    """Request body for POST /telemetry/interpret.

    `metrics` is a flat map of raw metric name to reading, e.g.
    `{"eff": 85, "o2pp": 158, "humidity": 34}` for the oxygen sector — see
    the per-sector `state` shapes in `mission-console.html`'s Module 02.
    """

    sector_id: str = Field(min_length=1)
    metrics: dict[str, float] = Field(min_length=1)


class TelemetryInterpretResponse(BaseModel):
    """Response body for POST /telemetry/interpret.

    `confidence` is derived from retrieval strength and distance from the
    nominal band the readings are checked against (see
    `app.services.telemetry._combine_confidence`), never a random or
    fabricated placeholder number. It stays optional (`float | None`)
    rather than a required `float`: a future retrieval implementation that
    can't produce a relevance score should be able to omit it honestly
    instead of forcing a number, the same reasoning that left it `None`
    before confidence scoring existed at all.
    """

    summary: str
    confidence: float | None = None
    source: str


class CrisisEvent(BaseModel):
    """A single entry from Module 01's live event feed."""

    timestamp: str = Field(min_length=1)
    sector: str = Field(min_length=1)
    description: str = Field(min_length=1)


class CrisisAnalyzeRequest(BaseModel):
    """Request body for POST /crisis/analyze."""

    events: list[CrisisEvent] = Field(min_length=1)


class CrisisAnalyzeResponse(BaseModel):
    """Response body for POST /crisis/analyze.

    `root_cause` is generated by the instruct model, grounded strictly in
    the single retrieved procedure chunk's excerpt (see
    `app.services.crisis.analyze_crisis`) — never in the event feed alone.
    `steps` comes from `app.services.extraction.extract_procedure_steps`,
    not from the model, so the step list is exactly what the procedure
    document says rather than a generated paraphrase of it — but it's run
    against the retrieved chunk's `doc_text` metadata (the full source
    document `app.services.ingestion.Chunk` carries), not the chunk's own
    excerpt text. That's dev plan Aug 20 Task 2 ("Ground the procedure
    steps in the retrieved procedure document"): the chunk's own text lost
    its line structure during chunking (see `Chunk`'s docstring), so
    `steps` reflects the source document as a whole rather than whatever
    fragment of it a single embedded chunk happens to contain.
    """

    root_cause: str
    steps: list[str]
    source: str


class TriageRequest(BaseModel):
    """Request body for POST /triage.

    `crew_member_id` is looked up as an exact match against an ingested
    crew file's `doc_id` (see `app.services.triage.run_triage`), not
    matched semantically the way `sector_id`/event feeds are — it gets
    interpolated into a Milvus boolean `expr` filter, so the pattern
    constraint below also doubles as expr-injection protection: only
    lowercase-slug ids (matching the existing crew ids in
    `mission-console.html`, e.g. `kim`, `okafor`) are accepted, which rules
    out a stray `'` breaking or widening the filter.
    """

    crew_member_id: str = Field(min_length=1, pattern=r"^[a-z0-9_-]+$")
    symptom_report: str = Field(min_length=1)


class TriageResponse(BaseModel):
    """Response body for POST /triage.

    `triage_lead` is generated by the instruct model, grounded in the
    single retrieved treatment protocol chunk's excerpt plus the retrieved
    crew file's full text (see `app.services.triage.run_triage`) — never in
    the symptom report alone. `instructions` comes from
    `app.services.extraction.extract_procedure_steps`, not from the model,
    read off the protocol chunk's `doc_text` metadata rather than its own
    excerpt text — the same chunk-boundary/line-structure grounding fix dev
    plan Aug 20 Task 2 had to add to `/crisis/analyze`'s `steps` after the
    fact (see `CrisisAnalyzeResponse`'s docstring), applied here from the
    start instead of repeated as a follow-up.

    `allergy_check` and `confidence` are both optional (`None` by default)
    for this commit: dev plan Aug 21 Task 2 ("Add the allergy cross check
    and the source reference line to the triage response") is a separate,
    later commit that fills `allergy_check` in for real. `confidence` is
    computed now from retrieval strength on the protocol match (see
    `app.services.triage._retrieval_strength`) rather than left `None` too,
    since the dev plan gives triage no dedicated confidence-scoring task
    the way telemetry (Aug 19 Task 2) and crisis (Aug 20 Task 2) got —
    leaving it `None` here would orphan the field with no task to fill it.
    Still `float | None` rather than a required `float`, matching
    `TelemetryInterpretResponse.confidence`'s reasoning: a retrieval
    implementation that can't produce a relevance score should be able to
    omit it honestly.
    """

    triage_lead: str
    instructions: list[str]
    allergy_check: str | None = None
    confidence: float | None = None
